name: CI/CD Pipeline for Proxy Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configuraci贸n de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construcci贸n de la imagen Docker
      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ secrets.APP_TAG }} .

      # Paso 4: Iniciar sesi贸n en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Push de la imagen Docker a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP_NAME }}:${{ secrets.DOCKER_APP_TAG }}